<a href="https://colab.research.google.com/github/YathapuYaswanth/ML_LAB/blob/main/numpy_AP23110010623.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.array([0,1,2])
print(type(a))
print(a.shape)
print(a[0])
print(a[1])
print(a[2])
a[0] = 5
print(a)
b = np.array([[0,1,2],[3,4,5]])
print(b.shape)
print(b[0,0],b[0,1],b[1,0])
print(b)


<class 'numpy.ndarray'>
(3,)
0
1
2
[5 1 2]
(2, 3)
0 1 3
[[0 1 2]
 [3 4 5]]


In [ ]:
import numpy as np

a = np.zeros((3,3))
b = np.ones((2,2))
c = np.full((3,3), 7)
d = np.random.random((3,3))
e = np.eye(3)
f = np.array([2,3,1,0])
g = np.arange(20)
h = np.array([[0,1,2.0],[0,0,0], (1+1j, 3., 2.)])
i = np.arange(1,8, dtype=float)
j = np.linspace(2, 4, 5)


In [ ]:
x = np.array([0,1])
y = np.array([2.0,3.0])
z = np.array([5,6],dtype = np.int64)
print(x.dtype, y.dtype, z.dtype)

int64 float64 int64


In [ ]:
import numpy as np
arr = np.array([[-1,2,0,4],[4,-0.5,6,0],[2.6,0,7,8],[3,-7,4,2.0]])
#slicing array
temp = arr[:2,::2]
print("Array with first 2 rows and alternate colummns(0 and 2):\n",temp)
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print ("\nElements at indices (0, 3), (1, 2), (2, 1),(3, 0):\n", temp)
cond = arr > 0
temp = arr[cond]
print("\nElements greater than 0:\n",temp)

Array with first 2 rows and alternate colummns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]

Elements at indices (0, 3), (1, 2), (2, 1),(3, 0):
 [4. 6. 0. 3.]

Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


In [ ]:
import numpy as np
a = np.array([1,2,5,3])
print("adding 1 for the every element:",a+1)
print("subtracting 3 to every element:",a-3)
print("multiplying each element by 10:",a*10)
print("square each element:",a ** 2)
a *= 2
print("Doubled each element of original array:",a)
a = np.array([[1,2,3],[3,4,5],[9,6,0]])
print("\nOriginal array:\n",a)
print("Transpose of array:\n",a.T)

adding 1 for the every element: [2 3 6 4]
subtracting 3 to every element: [-2 -1  2  0]
multiplying each element by 10: [10 20 50 30]
square each element: [ 1  4 25  9]
Doubled each element of original array: [ 2  4 10  6]

Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


In [ ]:
import numpy as np
arr = np.array([[1,5,6],[4,7,2],[3,1,9]])
print(arr.max())
print(arr.max(axis = 1))
print(arr.min())
print(arr.min(axis = 0))
print(arr.sum())
print(arr.cumsum(axis = 1))

9
[6 7 9]
1
[1 1 2]
38
[[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


In [ ]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[4,3],[2,1]])
print("array sum:",a+b)
print("array multiplication:",a*b)
print("matrix multiplication",a.dot(b))

array sum: [[5 5]
 [5 5]]
array multiplication: [[4 6]
 [6 4]]
matrix multiplication [[ 8  5]
 [20 13]]


In [ ]:
import numpy as np
a = np.array([0, np.pi/2, np.pi])
print ("Sine values of array elements:", np.sin(a))
a = np.array([0, 1, 2, 3])
print ("Exponent of array elements:", np.exp(a))
print ("Square root of array elements:", np.sqrt(a))

In [ ]:
import numpy as np
arr = np.array([[-1, 2, 0, 4],
[4, -0.5, 6, 0],
[2.6, 0, 7, 8],
[3, -7, 4, 2.0]])
inverse = np.linalg.inv(arr)
inverse

array([[ 4.05707196,  1.98511166, -2.28287841,  1.01736973],
       [ 0.50620347,  0.30272953, -0.24813896, -0.01985112],
       [-2.66253102, -1.13151365,  1.50124069, -0.67990074],
       [ 1.01116625,  0.34491315, -0.44665012,  0.26426799]])

In [ ]:
data = np.loadtxt("/content/fitness.txt", dtype="str")

/tmp/ipython-input-138286748.py:1: UserWarning: Input line 1 contained no data and will not be counted towards `max_rows=50000`.  This differs from the behaviour in NumPy <=1.22 which counted lines rather than rows.  If desired, the previous behaviour can be achieved by using `itertools.islice`.
Please see the 1.23 release notes for an example on how to do this.  If you wish to ignore this warning, use `warnings.filterwarnings`.  This warning is expected to be removed in the future and is given only once per `loadtxt` call.
  data = np.loadtxt("/content/fitness.txt", dtype="str")


In [ ]:
import numpy as np

data = np.loadtxt("/content/fitness.txt", dtype="str")

/tmp/ipython-input-1544400769.py:3: UserWarning: Input line 1 contained no data and will not be counted towards `max_rows=50000`.  This differs from the behaviour in NumPy <=1.22 which counted lines rather than rows.  If desired, the previous behaviour can be achieved by using `itertools.islice`.
Please see the 1.23 release notes for an example on how to do this.  If you wish to ignore this warning, use `warnings.filterwarnings`.  This warning is expected to be removed in the future and is given only once per `loadtxt` call.
  data = np.loadtxt("/content/fitness.txt", dtype="str")


In [ ]:
print(data[:44])

[['06-10-2017' '5464' '200' '181' '5' '0' '66']
 ['07-10-2017' '6041' '100' '197' '8' '0' '66']
 ['08-10-2017' '25' '100' '0' '5' '0' '66']
 ['09-10-2017' '5461' '100' '174' '4' '0' '66']
 ['10-10-2017' '6915' '200' '223' '5' '500' '66']
 ['11-10-2017' '4545' '100' '149' '6' '0' '66']
 ['12-10-2017' '4340' '100' '140' '6' '0' '66']
 ['13-10-2017' '1230' '100' '38' '7' '0' '66']
 ['14-10-2017' '61' '100' '1' '5' '0' '66']
 ['15-10-2017' '1258' '100' '40' '6' '0' '65']
 ['16-10-2017' '3148' '100' '101' '8' '0' '65']
 ['17-10-2017' '4687' '100' '152' '5' '0' '65']
 ['18-10-2017' '4732' '300' '150' '6' '500' '65']
 ['19-10-2017' '3519' '100' '113' '7' '0' '65']
 ['20-10-2017' '1580' '100' '49' '5' '0' '65']
 ['21-10-2017' '2822' '100' '86' '6' '0' '65']
 ['22-10-2017' '181' '100' '6' '8' '0' '65']
 ['23-10-2017' '3158' '200' '99' '5' '0' '65']
 ['24-10-2017' '4383' '200' '143' '4' '0' '64']
 ['25-10-2017' '3881' '200' '125' '5' '0' '64']
 ['26-10-2017' '4037' '200' '129' '6' '0' '64']
 ['2

In [ ]:
data[0]


array(['06-10-2017', '5464', '200', '181', '5', '0', '66'], dtype='<U10')

In [ ]:
data.T

array([['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
        '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
        '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
        '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
        '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
        '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
        '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
        '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
        '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
        '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
        '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
        '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
        '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
        '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
        '05-12-2017', '06-12-2017', '07-

In [ ]:
data1=np.array([[1,2,3]])
print(data1)


[[1 2 3]]


In [ ]:
data1.T


array([[1],
       [2],
       [3]])